# permissions for end users to edit healthchecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: healthcheck-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oper
    app.kubernetes.io/part-of: oper
    app.kubernetes.io/managed-by: kustomize
  name: healthcheck-editor-role
rules:
- apiGroups:
  - webapp.udaykk.me
  resources:
  - healthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.udaykk.me
  resources:
  - healthchecks/status
  verbs:
  - get
