---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - webapp.udaykk.me
  resources:
  - healthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.udaykk.me
  resources:
  - healthchecks/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.udaykk.me
  resources:
  - healthchecks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - webapp.udaykk.me
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
