name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
    - name: Install dependencies
      run: go get .
    - name: Build
      run: go build -v ./...
    - name: Test with the Go CLI
      run: go test    
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.UKK_GH_TOKEN }} 
      run: npx semantic-release
